server:
  port: 9090
spring:
  datasource:
          url: jdbc:mysql://localhost:3307/spring
          username: root
          password: 0070
          driver-class-name: com.mysql.cj.jdbc.Driver




